services:
  captcha-solver:
    image: ghcr.io/fkryakbar/ai-captcha-solver:latest
    container_name: ai_captcha_solver
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./screenshots:/app/screenshots
